DATASET_FOLDER = '/home/akmaral/tubCloud/Shared/cvmrs/training_dataset/synth/mrs/500/raw-images/'
# DATASET_FOLDER = 'aideck-dataset/imageStorage'
INPUT_CHANNEL = 1 # RGB: 3, Grey: 1
LOCA_STRIDE     = 8
LOCA_CLASSES    = {0: "crazyflie"}
TRAIN_ANNOT_PATH    = "{}../locanet/train.txt".format(DATASET_FOLDER)
TEST_PATH    = "{}../locanet/test.txt".format(DATASET_FOLDER)
TRAIN_BATCH_SIZE    = 8
TRAIN_INPUT_SIZE    = [320, 320]
TRAIN_LR_INIT       = 1e-3
TRAIN_LR_END        = 1e-6
TRAIN_WARMUP_EPOCHS = 2
TRAIN_EPOCHS        = 10
OUTPUT_FILE = 'synth-1k' #-refine'
WEIGHT_PATH = '/home/akmaral/tubCloud/Shared/cvmrs/trained-models/locanet/'
INFERENCE_FILE = "{}../locanet/inference_locanet.yaml".format(DATASET_FOLDER) # saves in 1k