INPUT_CHANNEL: 1 # RGB: 3, Grey: 1
LOCA_STRIDE:   8
LOCA_CLASSES: {0: "crazyflie"}
TRAIN_ANNOT_PATH: "/home/whoenig/imrc/cv-mrs/dataset/synth/3000/locanet/train.txt"
TRAIN_BATCH_SIZE: 8
TRAIN_INPUT_SIZE: [320, 320]
TRAIN_LR_INIT: 1e-3
TRAIN_LR_END: 1e-6
TRAIN_WARMUP_EPOCHS: 2
TRAIN_EPOCHS: 10
OUTPUT_FILE: 'synth-3k'
WEIGHT_PATH: '/home/whoenig/imrc/cv-mrs/models/'
INITIAL_WEIGHTS: ""
